services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_DB: "utf-account-service-postgres-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
        - "5432:5432"
