version: "3"

tasks:
    run-local:
        cmds:
            - go run ./cmd/app/main.go --config ./config/app/local.yml
    migrate-local:
        cmds:
        - go run ./cmd/migrator/migrate.go --config ./config/migrator/local.yml
